# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = bsp.out
SRCS = main.cpp Fixed.cpp Point.cpp bsp.cpp

include ../template.mk

main.cpp Fixed.cpp Point.cpp bsp.cpp: Fixed.hpp
main.cpp Point.cpp bsp.cpp: Point.hpp
