# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = test2_fixed.out
SRCS = main.cpp Fixed.cpp

include ../template.mk

main.cpp Fixed.cpp: Fixed.hpp
